/**
 * Headless balance report: plays N seeded matches with the default config and
 * the scripted bot, then writes docs/BALANCE.md. Run with `pnpm balance`
 * (Node strips the types; Vite's module runner resolves the app's TS imports).
 *
 *   pnpm balance            # 50 seeds, writes docs/BALANCE.md
 *   pnpm balance --seeds 10 # quicker, prints only (no file written)
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { format, resolveConfig } from 'prettier';
import { runnerImport } from 'vite';
import type * as BalanceModule from '../src/game/core/testing/balance.ts';
import type * as DefaultsModule from '../src/config/defaults.ts';

const DEFAULT_SEEDS = 50;
const root = path.resolve(import.meta.dirname, '..');
const outFile = path.join(root, 'docs', 'BALANCE.md');

const seedsArg = process.argv.indexOf('--seeds');
const seedCount = seedsArg > 0 ? Number(process.argv[seedsArg + 1]) : DEFAULT_SEEDS;
if (!Number.isInteger(seedCount) || seedCount < 1) {
  throw new Error(`--seeds must be a positive integer, got ${process.argv[seedsArg + 1]}`);
}

const load = async <T>(file: string): Promise<T> =>
  (await runnerImport<T>(path.join(root, file), { configFile: false, root, logLevel: 'error' }))
    .module;

const { playBalanceMatch } = await load<typeof BalanceModule>('src/game/core/testing/balance.ts');
const { DEFAULT_GAME_CONFIG: cfg } = await load<typeof DefaultsModule>('src/config/defaults.ts');

const samples = Array.from({ length: seedCount }, (_, i) => playBalanceMatch(cfg, i + 1));

const mean = (xs: readonly number[]): number => xs.reduce((s, x) => s + x, 0) / xs.length;
function median(xs: readonly number[]): number {
  const sorted = [...xs].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 1
    ? (sorted[mid] ?? 0)
    : ((sorted[mid - 1] ?? 0) + (sorted[mid] ?? 0)) / 2;
}
const fmt = (x: number, digits = 1): string => x.toFixed(digits);
const pct = (n: number): string => `${fmt((100 * n) / samples.length, 0)} %`;

const durations = samples.map((s) => s.durationSeconds);
const scores = samples.map((s) => s.score);
const timeUp = samples.filter((s) => s.endReason === 'time_up');
const defeated = samples.filter((s) => s.endReason === 'defeated');
const chasers = mean(samples.map((s) => s.spawnedByKind.chaser));
const shooters = mean(samples.map((s) => s.spawnedByKind.shooter));

const draft = `# Balance report

Generated by \`pnpm balance\` ([scripts/balance.ts](../scripts/balance.ts)): ${samples.length}
headless matches (seeds 1–${samples.length}) with the **default config**
([src/config/defaults.ts](../src/config/defaults.ts)) and the deterministic scripted bot
([src/game/core/testing/scriptedBot.ts](../src/game/core/testing/scriptedBot.ts)). Same code and
seeds ⇒ same numbers; rerun after any balancing change.

The bot is a rough proxy for a player (sails at the nearest enemy, turns broadside when close,
fires whatever bears, ignores islands), so these numbers describe the *shape* of a match rather
than human difficulty.

Config: session ${cfg.match.sessionSeconds} s · spawn every ${cfg.spawn.intervalSeconds} s · weights chaser ${cfg.spawn.weights.chaser} / shooter ${cfg.spawn.weights.shooter} · player HP ${cfg.ships.player.maxHp}.

| Metric                        | Mean | Median |
| ----------------------------- | ---- | ------ |
| Match duration (s)            | ${fmt(mean(durations))} | ${fmt(median(durations))} |
| Score (enemies destroyed)     | ${fmt(mean(scores))} | ${fmt(median(scores))} |
| Chasers spawned               | ${fmt(chasers)} | — |
| Shooters spawned              | ${fmt(shooters)} | — |

| End reason | Matches | Share |
| ---------- | ------- | ----- |
| time_up    | ${timeUp.length} | ${pct(timeUp.length)} |
| defeated   | ${defeated.length} | ${pct(defeated.length)} |
`;

// Same formatting as the rest of the repo, so `pnpm format:check` stays green.
const report = await format(draft, { ...(await resolveConfig(outFile)), parser: 'markdown' });
console.log(report);
if (seedsArg < 0) {
  await writeFile(outFile, report);
  console.log(`Wrote ${path.relative(root, outFile)}`);
}
