/**
 * Headless balance report: plays the same seeded matches with every scripted bot
 * profile (naive, skilled) on the default config, then writes docs/BALANCE.md.
 * Run with `pnpm balance` (Node strips the types; Vite's module runner resolves
 * the app's TS imports).
 *
 *   pnpm balance            # 50 seeds, writes docs/BALANCE.md
 *   pnpm balance --seeds 10 # quicker, prints only (no file written)
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { format, resolveConfig } from 'prettier';
import { runnerImport } from 'vite';
import type * as BalanceModule from '../src/game/core/testing/balance.ts';
import type * as BotsModule from '../src/game/core/testing/bots.ts';
import type * as DefaultsModule from '../src/config/defaults.ts';

const DEFAULT_SEEDS = 50;
const root = path.resolve(import.meta.dirname, '..');
const outFile = path.join(root, 'docs', 'BALANCE.md');

const seedsArg = process.argv.indexOf('--seeds');
const seedCount = seedsArg > 0 ? Number(process.argv[seedsArg + 1]) : DEFAULT_SEEDS;
if (!Number.isInteger(seedCount) || seedCount < 1) {
  throw new Error(`--seeds must be a positive integer, got ${process.argv[seedsArg + 1]}`);
}

const load = async <T>(file: string): Promise<T> =>
  (await runnerImport<T>(path.join(root, file), { configFile: false, root, logLevel: 'error' }))
    .module;

const { playBalanceMatch } = await load<typeof BalanceModule>('src/game/core/testing/balance.ts');
const { BOT_PROFILE_NAMES } = await load<typeof BotsModule>('src/game/core/testing/bots.ts');
const { DEFAULT_GAME_CONFIG: cfg } = await load<typeof DefaultsModule>('src/config/defaults.ts');

type Sample = ReturnType<typeof playBalanceMatch>;

const mean = (xs: readonly number[]): number => xs.reduce((s, x) => s + x, 0) / xs.length;
function median(xs: readonly number[]): number {
  const sorted = [...xs].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 1
    ? (sorted[mid] ?? 0)
    : ((sorted[mid - 1] ?? 0) + (sorted[mid] ?? 0)) / 2;
}
const fmt = (x: number, digits = 1): string => x.toFixed(digits);
const share = (n: number): string => `${fmt((100 * n) / seedCount, 0)} %`;

const results = BOT_PROFILE_NAMES.map((profile) => ({
  profile,
  samples: Array.from({ length: seedCount }, (_, i) => playBalanceMatch(cfg, i + 1, profile)),
}));

const metrics: readonly [string, (s: Sample) => number, boolean][] = [
  ['Match duration (s)', (s) => s.durationSeconds, true],
  ['Score (enemies destroyed)', (s) => s.score, true],
  ['Chasers spawned', (s) => s.spawnedByKind.chaser, false],
  ['Shooters spawned', (s) => s.spawnedByKind.shooter, false],
];

const header = `| Metric | ${results.map((r) => `${r.profile} mean | ${r.profile} median`).join(' | ')} |`;
const divider = `| --- | ${results.map(() => '--- | ---').join(' | ')} |`;
const metricRows = metrics.map(([label, pick, withMedian]) => {
  const cells = results.map(({ samples }) => {
    const values = samples.map(pick);
    return `${fmt(mean(values))} | ${withMedian ? fmt(median(values)) : '—'}`;
  });
  return `| ${label} | ${cells.join(' | ')} |`;
});

const endHeader = `| End reason | ${results.map((r) => `${r.profile} matches | ${r.profile} share`).join(' | ')} |`;
const endRows = (['time_up', 'defeated'] as const).map((reason) => {
  const cells = results.map(({ samples }) => {
    const n = samples.filter((s) => s.endReason === reason).length;
    return `${n} | ${share(n)}`;
  });
  return `| ${reason} | ${cells.join(' | ')} |`;
});

const draft = `# Balance report

Generated by \`pnpm balance\` ([scripts/balance.ts](../scripts/balance.ts)): ${seedCount}
headless matches per bot profile (seeds 1–${seedCount}, the same seeds for every profile) with the
**default config** ([src/config/defaults.ts](../src/config/defaults.ts)). Same code and seeds ⇒
same numbers; rerun after any balancing change.

Bot profiles ([src/game/core/testing/](../src/game/core/testing/)):

- **naive** — sails straight at the nearest enemy, ignores islands and Chasers, fires whatever
  bears; reacts every step. A lower bound.
- **skilled** — decides every 0.2 s (human-like reaction time), kites Chasers that come within
  200 u, routes around islands with the flow field, keeps off shores and the arena edge, and
  taps a trigger only when that weapon bears. The balancing target applies to this profile:
  median duration 60–100 s and 20–50 % of matches ending by time_up.

Both are proxies for a human player: the numbers describe the shape of a match, and final tuning
is validated by manual play.

Config: session ${cfg.match.sessionSeconds} s · spawn every ${cfg.spawn.intervalSeconds} s · weights chaser ${cfg.spawn.weights.chaser} / shooter ${cfg.spawn.weights.shooter} · chaser speed ${cfg.ships.chaser.maxSpeed} u/s · ram damage ${cfg.chaser.ramDamage} · player HP ${cfg.ships.player.maxHp}.

${header}
${divider}
${metricRows.join('\n')}

${endHeader}
${divider}
${endRows.join('\n')}
`;

// Same formatting as the rest of the repo, so `pnpm format:check` stays green.
const report = await format(draft, { ...(await resolveConfig(outFile)), parser: 'markdown' });
console.log(report);
if (seedsArg < 0) {
  await writeFile(outFile, report);
  console.log(`Wrote ${path.relative(root, outFile)}`);
}
